name: cConomy
version: 1.00
author: CainFool
main: main.java.me.cain.cconomy.cConomy
commands:
   money:
       description: 'Money commands'
   pay:
       description: 'Pay a user'
   startermoney:
       description: 'Set the default starter money'
   createaccount:
       description: 'Create an account'
   removeaccount:
       description: 'Remove an account'